### ISSUE TITLE
Certain CRSs mistreat `minZoom`

### ISSUE THREAD

**Issue by JosefWN** [fleaflet/flutter_map#1358]
### What is the bug?

I get the following exception when zooming out as far as possible without explicitly setting `minZoom` to 0:
```
                      ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
                      The following RangeError was thrown while handling a gesture:
                      RangeError (index): Invalid value: Not in inclusive range 0..14: -1
                      
                      When the exception was thrown, this was the stack:
                      #0      _Array.[] (dart:core-patch/array.dart:10:36)
                      #1      Proj4Crs.scale (package:flutter_map/src/geo/crs/crs.dart:289:32)
                      #2      FlutterMapState.getZoomScale (package:flutter_map/src/map/flutter_map_state.dart:567:16)
                      #3      FlutterMapState.getPixelBounds (package:flutter_map/src/map/flutter_map_state.dart:592:19)
                      #4      FlutterMapState.move (package:flutter_map/src/map/flutter_map_state.dart:457:20)
                      #5      MapGestureMixin.handleScaleUpdate (package:flutter_map/src/gestures/gestures.dart:452:35)
                      #6      ScaleGestureRecognizer._advanceStateMachine.<anonymous closure> (package:flutter/src/gestures/scale.dart:642:18)
                      #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
                      #8      ScaleGestureRecognizer._advanceStateMachine (package:flutter/src/gestures/scale.dart:641:7)
                      #9      ScaleGestureRecognizer.handleEvent (package:flutter/src/gestures/scale.dart:497:7)
                      #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
                      #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
                      #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
                      #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
                      #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
                      #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
                      #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
                      #17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
                      #18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
                      #19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
                      #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
                      #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
                      #22     _invoke1 (dart:ui/hooks.dart:167:13)
                      #23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
                      #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
                      
                      Handler: "onUpdate"
                      Recognizer:
                        ScaleGestureRecognizer#9330d
```

### What is the expected behaviour?

I would expect the default for `minZoom` to be 0 if not set (or make the parameter required, if it is).

### How can we reproduce this issue?

```dart
Omit `minZoom` in the options, zoom out as far as possible.
```

### Can you provide any other information?

This is on `flutter_map` 3.0.0.

### Platforms Affected

MacOS

### Severity

Minimum: Allows normal functioning

### Frequency

Consistently: Always occurs at the same time and location

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/fleaflet/flutter_map/blob/master/CODE_OF_CONDUCT.md)
- [X] My Flutter/Dart installation is unaltered, and `flutter doctor` finds no relevant issues
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map) of this package
- [X] I have checked the FAQs section on the documentation website
- [X] I have checked for similar issues which may be duplicates
