### ISSUE TITLE
[BUG] `fitBounds` doesn't cause new tiles to load

### ISSUE THREAD

**Issue by billyz313** [fleaflet/flutter_map#1563]
### What is the bug?

When I use the .fitBounds method the map moves to the correct location, however the tiles which are supposed to be displayed on the map do not load.  If I slightly pan or zoom the map the tiles show up.  This happens in the web version when running thru the Chrome browser.  It works fine in the android version.  You can see it happening in the image below.

![fitBoundsExample](https://github.com/fleaflet/flutter_map/assets/1868821/d94f052e-937b-4c24-8ce6-f6f5950c1ea9)

### How can we reproduce it?

I removed the small bit of code from the search and hard coded the values so the code to reproduce can be as simple as 

```
widget.controller.fitBounds(LatLngBounds(
                      LatLng(46.3471572, 0.0527585),
                      LatLng(48.9410263, 3.1286392)));
```

I work around it by programmatically moving the map directly after the fitBounds and it works, but I feel like it should be able to just fitBounds to show the tiles.

### Platforms

Windows, visual studio code, Chrome(web-javascript), debug

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment]
Hi @billyz313,

Thanks for the report. This is strange that it only affects certain platforms.
Can you please confirm your flutter_map version?

If you have the spare time, please try depending on #1551, as that may or may not solve this issue. A pubspec.yaml snippet to do this is:

```yaml
dependency_overrides:
    flutter_map:
        git:
            url: https://github.com/rorystephenson/flutter_map.git
            ref: flutter-map-state-refactor
```

**Comment by billyz313** [comment]
My pleasure, I also found it strange.  

In my pubspec i currently have flutter_map: ^4.0.0.

Unfortunately I can't use the flutter_map in the repo because I am using flutter_map_dragmarker and flutter_map_line_editor which throw a bunch of errors all seeming to lead back to stuff like "The getter 'FlutterMapState' isn't defined for the class 'DragMarkers'."  So I assume those just are not ready for the new version...

**Comment by billyz313** [comment]
@ibrierley Thank you, I do have the updated ones for v5, however they seem to not work with the dependency_overrides suggestion from above

```
dependency_overrides:
    flutter_map:
        git:
            url: https://github.com/rorystephenson/flutter_map.git
            ref: flutter-map-state-refactor
```
