### ISSUE TITLE
Add wms?

### ISSUE THREAD

**Issue by klaszlo8207** [fleaflet/flutter_map#537]
The name parameter wmsOptions is not defined on the widget :(

How to solve that?

**Comment by maRci002** [comment]
Current version on [pub](https://pub.dev/packages/flutter_map/versions) is 0.8.2 which not includes wmsOptions.

However you can still use it, just change your dependecy to:
```
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: master
```
