### ISSUE TITLE
Problem with multiple WMS layer

### ISSUE THREAD

**Issue by alenvieira** [fleaflet/flutter_map#589]
I'm using it as a dependencies:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: master
```
And code:

```

FlutterMap(
    options: MapOptions(
      crs: Epsg4326(),
      center: LatLng(-15.794, -47.882),
      zoom: 4,
    ),
    layers: [
      TileLayerOptions(
        wmsOptions: WMSTileLayerOptions(
          crs: Epsg4326(),
          baseUrl: 'https://tiles.maps.eox.at/?',
          layers: ['s2cloudless-2019', 'overlay_base'],
        ),
      ),
      TileLayerOptions(
        wmsOptions: WMSTileLayerOptions(
          crs: Epsg4326(),
          baseUrl: 'https://firms.modaps.eosdis.nasa.gov/wms/key/bb434bf37c7522d00d472e340ceab7b6/?',
          layers: ['fires_viirs_7'],
        ),
      ),
    ],
  )
```
The second wms layer (nasa layer is point layer) is not transparent. Why?
