### ISSUE TITLE
Map kinda blurry when using tiles from Google Street

### ISSUE THREAD

**Issue by brizaldi** [fleaflet/flutter_map#613]
So, i'm using custom tile from Google Street
```
TileLayerOptions(
  urlTemplate: 'http://mt{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
  subdomains: ['0','1','2','3'],
  tileProvider: NonCachingNetworkTileProvider(),
),
```
but, the displayed map is kinda blurry

here is the example from the official `google_maps_flutter` library:
![image](https://user-images.githubusercontent.com/41714881/81541055-c1926700-939c-11ea-9562-820b85f5b251.png)
and then here is from the leaflet library
![image](https://user-images.githubusercontent.com/41714881/81541051-c0613a00-939c-11ea-913c-c30897ac47f1.png)

**Comment by maRci002** [comment]
PR #585 maybe helps, just set `retinaMode` to `true` on `TileLayerOptions`.

**Comment by hahazheng** [comment]
> ```dart
>             retinaMode: retina,
> ```

Can't find this parameter,  retinaMode: retina, why

**Comment by maRci002** [comment]
Becuase only PR #585 has those modifications, but you can use it if you clone this repo, or you can change flutter_map dependency in your `pubspec.yaml` and then run `flutter pub upgrade`
```
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: b41932100ba8af15326560384d6667b4bd087c35
```
