### ISSUE TITLE
onTap, onLongPress handlers break after map rotation

### ISSUE THREAD

**Issue by eae1212** [fleaflet/flutter_map#700]
I have added onTap handler for the page map_controller of the example project. It just printed position coordinates. After map rotation nothing occurs. The same behavior for onLongPress handler.

**Comment by maRci002** [comment]
Can you try PR #695 maybe it fixes, you don't have to provide any key.

**Comment by eae1212** [comment]
You mean upgrade flutter_map packages?

**Comment by maRci002** [comment]
You change your dependency like this in `pubspec.yaml`:

```
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: 25ca76141d6f09628a9d6da257687348a0244553
```

`ref: 25ca76141d6f09628a9d6da257687348a0244553` is the latest commit hash of the PR.
Then run `flutter pub get` or `flutter pub upgrade` to make sure you are using the fix.
