### ISSUE TITLE
Version config because of tuple and quiver

### ISSUE THREAD

**Issue by itsarnavsingh** [fleaflet/flutter_map#865]
I am getting the following error

```
Because flutter_map >=0.5.0+1 depends on tuple ^1.0.2 which depends on quiver >=0.22.0 <3.0.0, flutter_map >=0.5.0+1 requires quiver >=0.22.0 <3.0.0.

And because google_sign_in_platform_interface 2.0.1 depends on quiver ^3.0.0 and no versions of google_sign_in_platform_interface match >2.0.1 <3.0.0, flutter_map >=0.5.0+1 is incompatible with google_sign_in_platform_interface ^2.0.1.

And because google_sign_in 5.0.1 depends on google_sign_in_platform_interface ^2.0.1 and no versions of google_sign_in match >5.0.1 <6.0.0, flutter_map >=0.5.0+1 is incompatible with google_sign_in ^5.0.1.

So, because bestfella depends on both google_sign_in ^5.0.1 and flutter_map ^0.12.0, version solving failed.
pub get failed (1; So, because bestfella depends on both google_sign_in ^5.0.1 and flutter_map ^0.12.0, version solving failed.)
exit code 1


```

My pubspec.yaml is as following
```
name: bestfella
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  google_sign_in: ^5.0.1
  shared_preferences: ^2.0.0-nullsafety
  provider: ^5.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_map: ^0.12.0 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

```

**Comment by Vietdq-dev** [comment]
I have a solution
You can change version flutter map to
```
flutter_map:
    git:
      url: https://github.com/Vietdq-dev/flutter_map.git
      ref: nullsafety_viet
```
after flutter clean and flutter pub get
I hope help you
