### ISSUE TITLE
flutter_map trying to use latlng2 rather than latlng...

### ISSUE THREAD

**Issue by ibrierley** [fleaflet/flutter_map#882]
This is likely something to do with my own setup, but reaching out for any suggestions. 

I've just updated flutter_map and note the change with latlng needing it's own import. 

In my pubspec.yaml I have changed to latlong: ^0.6.1 (I think previously I may have had "any"

In my main.dart I have import 'package:latlong/latlong.dart';

However, when I try and run my project I get...
```
../../flutter/.pub-cache/hosted/pub.dartlang.org/latlong2-0.8.0/lib/latlong.dart:54:6: Error: Error when reading '../../flutter/.pub-cache/hosted/pub.dartlang.org/latlong2-0.8.0/lib/latlong/LatLng.dart': No such file or directory
part 'latlong/LatLng.dart';
```

I note in pubspec.lock it adds...
```
latlong:
    dependency: "direct main"
    description:
      name: latlong
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1"
  latlong2:
    dependency: transitive
    description:
      name: latlong2
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.0"
```

So it's trying to grab latlong2 for some reason as well as latlong and use that (i.e https://pub.dev/packages/latlong2/versions ). If I do a find on the whole project there is no mention of latlong2 at all.

Anyone have any thoughts ?
